--#SET TERMINATOR ;
SET CURRENT SCHEMA = 'DB2TEST';
SET CURRENT PATH = 'DB2TEST';

--#SET TERMINATOR @

BEGIN
  IF EXISTS (SELECT ROUTINENAME FROM SYSIBM.SYSROUTINES
    WHERE routineschema = 'DB2TEST' AND ROUTINENAME = 'TEST_DBMS_OUTPUT') THEN
      PREPARE stmt FROM 'DROP PROCEDURE DB2TEST.TEST_DBMS_OUTPUT';
      EXECUTE stmt;
  END if;
END
@