-- Test DBMSOUTPUT

--#SET TERMINATOR ;
SET CURRENT SCHEMA = 'DB2TEST';
SET CURRENT PATH = 'DB2TEST';
--SET CURRENT PATH 'SYSIBMADM';

--#SET TERMINATOR @
CREATE OR REPLACE PROCEDURE TEST_DBMS_OUTPUT()
LANGUAGE SQL
BEGIN
    CALL SYSIBMADM.DBMS_OUTPUT.PUT_LINE('This is some text from DBMS_OUTPUT called from within a procedure');
END
@

SET SERVEROUTPUT ON@

CALL SYSIBMADM.DBMS_OUTPUT.PUT_LINE('In line call using dbms output')@

CALL TEST_DBMS_OUTPUT() @

SET SERVEROUTPUT OFF@

CALL SYSIBMADM.DBMS_OUTPUT.PUT_LINE('In line call when output is disabled')@
