-- Some comment at the top

SET CURRENT SCHEMA = 'DB2TEST';
SET CURRENT PATH = 'DB2TEST';

--#SET TERMINATOR @
BEGIN
   IF EXISTS (SELECT TABNAME FROM SYSCAT.TABLES WHERE TABSCHEMA = 'DB2TEST' AND TABNAME = 'TEST') THEN
      PREPARE stmt FROM 'DROP TABLE DB2TEST.TEST';
      EXECUTE stmt;
   END IF;
END
@

BEGIN
   IF EXISTS (SELECT * FROM SYSCAT.SEQUENCES WHERE SEQSCHEMA = 'DB2TEST' AND SEQNAME = 'TEST_SEQ') THEN
      PREPARE stmt FROM 'DROP SEQUENCE DB2TEST.TEST_SEQ';
      EXECUTE stmt;
   END IF;
END
@

BEGIN
   IF EXISTS (SELECT TABNAME FROM SYSCAT.TABLES WHERE TABSCHEMA = 'DB2TEST' AND TABNAME = 'TEST_HISTORY') THEN
      PREPARE stmt FROM 'DROP TABLE DB2TEST.TEST_HISTORY';
      EXECUTE stmt;
   END IF;
END
@

BEGIN
  IF EXISTS (SELECT ROUTINENAME FROM SYSIBM.SYSROUTINES
    WHERE routineschema = 'DB2TEST' AND ROUTINENAME = 'TEST_PROC') THEN
      PREPARE stmt FROM 'DROP PROCEDURE DB2TEST.TEST_PROC';
      EXECUTE stmt;
  END if;
END
@

BEGIN
  IF EXISTS (SELECT ROUTINENAME FROM SYSIBM.SYSROUTINES
    WHERE routineschema = 'DB2TEST' AND ROUTINENAME = 'ANOTHER_PROC') THEN
      PREPARE stmt FROM 'DROP PROCEDURE DB2TEST.ANOTHER_PROC';
      EXECUTE stmt;
  END if;
END
@

--- End ---
