name: Release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release (defaults to main)'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Configure Git User
          run: |
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
      - name: Prepare and perform release with maven
        run: mvn -B -DtagNameFormat=v@{version} -DreleaseProfiles=gpg-sign -Darguments="-Dmaven.deploy.skip=true" release:prepare release:perform
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
